# -*- coding: utf-8 -*-
"""Sistema_Alertas_Climaticas_Santander_COMPLETO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozp_7wCHpcBhJXmJh6VgALW9WW9wMqY0

# Sistema Inteligente de Monitoreo Ambiental y Alertas Tempranas
## EDA enfocado en Santander

Este notebook realiza el Analisis Exploratorio de Datos (EDA) para el proyecto de monitoreo ambiental, enfocado en el departamento de **Santander, Colombia**.

### Fuentes de datos
- **Desastres naturales y antropicos** (datos.gov.co - IDEAM)
- **Temperatura ambiente del aire** (IDEAM)
- **Precipitacion** (IDEAM)
- **Humedad del aire** (IDEAM)

### Estrategia
1. Cargar primero los desastres (son pocos ~970 registros) para definir el alcance
2. Filtrar datos climaticos solo para Santander y el rango temporal de los desastres
3. Cruzar condiciones climaticas con eventos de desastre
4. Analizar patrones, anomalias y correlaciones

## 1. Configuracion

Instalacion de dependencias y configuracion del entorno de trabajo.
"""

!pip install sodapy -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sodapy import Socrata
import warnings
import unicodedata
from math import radians, cos, sin, asin, sqrt

warnings.filterwarnings('ignore')
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (14, 6)
plt.rcParams['font.size'] = 12

"""## 2. Carga de datos - Desastres

Cargamos **primero** el dataset de desastres porque es pequeno (~970 registros) y define el alcance geografico y temporal del proyecto.
"""

client = Socrata("www.datos.gov.co", None, timeout=60)

print("=" * 60)
print("CARGANDO DATASET DE DESASTRES (completo)")
print("=" * 60)
results_des = client.get("a4bc-a9tq", limit=5000)
df_desastres = pd.DataFrame.from_records(results_des)
print(f"Registros: {len(df_desastres):,}")
print(f"Columnas: {list(df_desastres.columns)}")
print(f"\nPrimeras filas:")
display(df_desastres.head(3))

"""## 3. Alcance geografico del dataset

**Hallazgo clave:** Los desastres registrados corresponden casi en su totalidad a las corporaciones autonomas **CAS** y **CDMB**, ambas de **Santander**.
"""

print("=" * 60)
print("ALCANCE GEOGRAFICO DEL DATASET DE DESASTRES")
print("=" * 60)

print("\nDistribucion por Autoridad Ambiental:")
print(df_desastres['autoridad_ambiental'].value_counts())

print("\n>> HALLAZGO: CAS y CDMB son corporaciones de Santander.")
print(">> El proyecto se enfoca en el departamento de Santander.\n")

df_desastres['autoridad_ambiental'] = df_desastres['autoridad_ambiental'].str.upper().str.strip()

df_desastres = df_desastres[
    df_desastres['autoridad_ambiental'].isin(['CAS', 'CDMB'])
].copy()
print(f"Registros de Santander (CAS + CDMB): {len(df_desastres):,}")

"""## 4. EDA de desastres en Santander

Analisis exploratorio de los eventos de desastre:
- Tipos de evento y su frecuencia
- Distribucion por municipio
- Patrones temporales (estacionalidad mensual y tendencia anual)
- Severidad de los eventos

### 4a. Tipos de evento y municipios afectados
"""

df_desastres['fecha_de_ocurrencia'] = pd.to_datetime(
    df_desastres['fecha_de_ocurrencia'], errors='coerce'
)

fecha_min = df_desastres['fecha_de_ocurrencia'].min()
fecha_max = df_desastres['fecha_de_ocurrencia'].max()
print(f"Rango temporal de desastres: {fecha_min.date()} a {fecha_max.date()}")

print("\n--- Tipos de desastres reportados ---")
tipo_counts = df_desastres['tipo_de_evento'].value_counts()
print(tipo_counts)

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

tipo_counts.plot(kind='barh', ax=axes[0], color=sns.color_palette('Reds_r', len(tipo_counts)))
axes[0].set_title('Tipos de desastres en Santander', fontweight='bold')
axes[0].set_xlabel('Cantidad de reportes')
axes[0].invert_yaxis()

muni_counts = df_desastres['municipio'].value_counts().head(15)
muni_counts.plot(kind='barh', ax=axes[1], color=sns.color_palette('YlOrRd', len(muni_counts)))
axes[1].set_title('Top 15 municipios con mas desastres', fontweight='bold')
axes[1].set_xlabel('Cantidad de reportes')
axes[1].invert_yaxis()

plt.suptitle('Desastres Naturales y Antropicos - Santander', fontsize=15, fontweight='bold')
plt.tight_layout()
plt.show()

"""### 4b. Patron temporal de desastres

Se espera correlacion con las temporadas de lluvia en Colombia (abril-mayo y octubre-noviembre).
"""

df_desastres['anio'] = df_desastres['fecha_de_ocurrencia'].dt.year
df_desastres['mes'] = df_desastres['fecha_de_ocurrencia'].dt.month

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

mes_counts = df_desastres.groupby('mes').size()
meses = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']
mes_counts.index = [meses[i-1] for i in mes_counts.index]
mes_counts.plot(kind='bar', ax=axes[0], color='#e67e22', alpha=0.8, edgecolor='black')
axes[0].set_title('Desastres por mes (estacionalidad)', fontweight='bold')
axes[0].set_ylabel('Cantidad')
axes[0].set_xlabel('Mes')

anio_counts = df_desastres.groupby('anio').size()
anio_counts.plot(ax=axes[1], marker='o', color='#e67e22', linewidth=2)
axes[1].set_title('Desastres por ano', fontweight='bold')
axes[1].set_ylabel('Cantidad')
axes[1].grid(True, alpha=0.3)

plt.suptitle('Patrones temporales de desastres - Santander', fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

print("\nNOTA: Se espera correlacion con temporadas de lluvia")
print("(abril-mayo y octubre-noviembre en Colombia).")

"""### 4c. Tipos de evento por mes"""

tipo_mes = pd.crosstab(df_desastres['mes'], df_desastres['tipo_de_evento'])
top_tipos = tipo_counts.head(5).index.tolist()
tipo_mes_top = tipo_mes[top_tipos] if all(t in tipo_mes.columns for t in top_tipos) else tipo_mes.iloc[:, :5]

fig, ax = plt.subplots(figsize=(14, 6))
tipo_mes_top.plot(kind='bar', ax=ax, stacked=True, colormap='Set2', edgecolor='black', alpha=0.85)
ax.set_title('Tipo de desastre por mes - Top 5 tipos', fontweight='bold', fontsize=14)
ax.set_xlabel('Mes')
ax.set_ylabel('Cantidad')
ax.set_xticklabels(meses, rotation=45)
ax.legend(title='Tipo de evento', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""### 4d. Severidad de los eventos

Indice de severidad compuesto: familias afectadas (x1) + viviendas destruidas (x5) + viviendas averiadas (x2) + heridos (x10) + fallecidos (x50).
"""

cols_severidad = ['familias_afectadas', 'viviendas_destruidas',
                  'viviendas_averiadas', 'heridos', 'fallecidos']
cols_presentes = [c for c in cols_severidad if c in df_desastres.columns]

if cols_presentes:
    for col in cols_presentes:
        df_desastres[col] = pd.to_numeric(df_desastres[col], errors='coerce').fillna(0)

    print("--- Severidad de los eventos ---")
    display(df_desastres[cols_presentes].describe().round(1))

    df_desastres['severidad'] = (
        df_desastres['familias_afectadas'] +
        df_desastres['viviendas_destruidas'] * 5 +
        df_desastres['viviendas_averiadas'] * 2 +
        df_desastres['heridos'] * 10 +
        df_desastres['fallecidos'] * 50
    )

    print(f"\nIndice de severidad (compuesto):")
    print(f"  Media: {df_desastres['severidad'].mean():.1f}")
    print(f"  Mediana: {df_desastres['severidad'].median():.1f}")
    print(f"  Max: {df_desastres['severidad'].max():.1f}")

    print("\n--- Top 10 eventos mas severos ---")
    top_severos = df_desastres.nlargest(10, 'severidad')[
        ['fecha_de_ocurrencia', 'tipo_de_evento', 'municipio', 'severidad'] + cols_presentes
    ]
    display(top_severos)

"""## 5. Carga de datos climaticos - Solo Santander

Hacemos **una consulta por ano** (2020-2024) con 50K registros cada una para obtener hasta **250K registros** distribuidos a lo largo de todo el periodo.

> **Nota:** Sin `app_token`, una sola consulta de 50K solo cubriria unos pocos meses. El enfoque por ano garantiza cobertura temporal completa.
"""

fecha_inicio = fecha_min.strftime('%Y-%m-%dT00:00:00')
fecha_fin = fecha_max.strftime('%Y-%m-%dT23:59:59')

print("=" * 60)
print(f"CARGANDO DATOS CLIMATICOS DE SANTANDER")
print(f"Rango: {fecha_min.date()} a {fecha_max.date()}")
print("=" * 60)

municipios_desastres = df_desastres['municipio'].dropna().unique().tolist()
print(f"\nMunicipios con desastres: {len(municipios_desastres)}")
print(municipios_desastres[:10], "...")

LIMIT_CLIMA = 50000
client_long = Socrata("www.datos.gov.co", None, timeout=120)

def cargar_clima_santander(dataset_id, nombre, client, limit_por_anio=50000):
    """Carga datos climaticos de Santander con una consulta por ano."""
    print(f"\nCargando {nombre} (Santander, 2020-2024)...")
    frames = []

    for anio in range(2020, 2025):
        where_clause = (
            f"departamento = 'SANTANDER' "
            f"AND fechaobservacion >= '{anio}-01-01T00:00:00' "
            f"AND fechaobservacion < '{anio+1}-01-01T00:00:00'"
        )
        try:
            results = client.get(dataset_id, where=where_clause, limit=limit_por_anio)
            df_anio = pd.DataFrame.from_records(results)
            if len(df_anio) > 0:
                frames.append(df_anio)
                print(f"  {anio}: {len(df_anio):,} registros")
            else:
                print(f"  {anio}: sin datos")
        except Exception as e:
            print(f"  {anio}: error - {e}")

    if frames:
        df = pd.concat(frames, ignore_index=True)
        print(f"  TOTAL: {len(df):,} registros")
        return df
    else:
        print(f"  ERROR: no se pudo cargar ningun ano")
        return pd.DataFrame()

df_temperatura = cargar_clima_santander("sbwg-7ju4", "Temperatura", client_long)
df_precipitacion = cargar_clima_santander("s54a-sgyg", "Precipitacion", client_long)
df_humedad = cargar_clima_santander("uext-mhny", "Humedad", client_long)

print("\n>> Resumen de carga:")
print(f"   Temperatura:   {len(df_temperatura):,} registros")
print(f"   Precipitacion: {len(df_precipitacion):,} registros")
print(f"   Humedad:       {len(df_humedad):,} registros")

"""## 6. Preprocesamiento de datos climaticos

Conversion de tipos, estandarizacion de municipios y eliminacion de nulos.
"""

def preparar_climatico(df, nombre):
    """Limpia y prepara un dataset climatico."""
    print(f"\n--- Preparando {nombre} ---")
    print(f"Columnas: {list(df.columns)}")
    print(f"Registros iniciales: {len(df):,}")

    df['fechaobservacion'] = pd.to_datetime(df['fechaobservacion'], errors='coerce')
    df['valorobservado'] = pd.to_numeric(df['valorobservado'], errors='coerce')

    if 'latitud' in df.columns:
        df['latitud'] = pd.to_numeric(df['latitud'], errors='coerce')
    if 'longitud' in df.columns:
        df['longitud'] = pd.to_numeric(df['longitud'], errors='coerce')

    if 'municipio' in df.columns:
        df['municipio'] = df['municipio'].str.upper().str.strip()

    antes = len(df)
    df = df.dropna(subset=['fechaobservacion', 'valorobservado'])
    print(f"Despues de eliminar nulos clave: {len(df):,} (eliminados: {antes - len(df):,})")

    print(f"Rango temporal: {df['fechaobservacion'].min().date()} a {df['fechaobservacion'].max().date()}")
    print(f"Valor: min={df['valorobservado'].min():.2f}, max={df['valorobservado'].max():.2f}, "
          f"media={df['valorobservado'].mean():.2f}")

    if 'municipio' in df.columns:
        print(f"Municipios: {df['municipio'].nunique()}")
    if 'codigoestacion' in df.columns:
        print(f"Estaciones: {df['codigoestacion'].nunique()}")

    return df

df_temperatura = preparar_climatico(df_temperatura, "Temperatura")
df_precipitacion = preparar_climatico(df_precipitacion, "Precipitacion")
df_humedad = preparar_climatico(df_humedad, "Humedad")

"""## 7. EDA climatico - Orientado al problema

### 7a. Distribucion de cada variable climatica
"""

fig, axes = plt.subplots(1, 3, figsize=(20, 6))

if len(df_temperatura) > 0:
    df_temperatura['valorobservado'].dropna().hist(
        bins=50, ax=axes[0], color='#e74c3c', alpha=0.7, edgecolor='black')
    axes[0].set_title('Temperatura (\u00b0C) - Santander', fontweight='bold')
    axes[0].set_xlabel('Temperatura')
    axes[0].axvline(df_temperatura['valorobservado'].mean(), color='black',
                    linestyle='--', label=f"Media: {df_temperatura['valorobservado'].mean():.1f}\u00b0C")
    axes[0].legend()

if len(df_precipitacion) > 0:
    df_precipitacion['valorobservado'].dropna().hist(
        bins=50, ax=axes[1], color='#3498db', alpha=0.7, edgecolor='black')
    axes[1].set_title('Precipitacion (mm) - Santander', fontweight='bold')
    axes[1].set_xlabel('Precipitacion')
    pct95 = df_precipitacion['valorobservado'].quantile(0.95)
    axes[1].axvline(pct95, color='red', linestyle='--', label=f"P95: {pct95:.1f}mm")
    axes[1].legend()

if len(df_humedad) > 0:
    df_humedad['valorobservado'].dropna().hist(
        bins=50, ax=axes[2], color='#27ae60', alpha=0.7, edgecolor='black')
    axes[2].set_title('Humedad (%) - Santander', fontweight='bold')
    axes[2].set_xlabel('Humedad relativa')
    axes[2].axvline(df_humedad['valorobservado'].mean(), color='black',
                    linestyle='--', label=f"Media: {df_humedad['valorobservado'].mean():.1f}%")
    axes[2].legend()

plt.suptitle('Distribuciones climaticas - Santander', fontsize=15, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""### 7b. Deteccion de anomalias por municipio

Z-scores **por municipio** (no globales): 35\u00b0C es normal en Barrancabermeja pero anomalo en Bucaramanga.
"""

print("=" * 60)
print("DETECCION DE ANOMALIAS POR MUNICIPIO")
print("=" * 60)

def detectar_anomalias_por_municipio(df, nombre_variable):
    if len(df) == 0 or 'municipio' not in df.columns or 'valorobservado' not in df.columns:
        print(f"  {nombre_variable}: sin datos o columnas")
        return df

    for col in ['media_muni', 'std_muni', 'z_score', 'es_anomalia']:
        if col in df.columns:
            df = df.drop(columns=[col])

    df = df.copy()
    df['media_muni'] = df.groupby('municipio')['valorobservado'].transform('mean')
    df['std_muni'] = df.groupby('municipio')['valorobservado'].transform('std')
    df['z_score'] = np.where(df['std_muni'] > 0,
        (df['valorobservado'] - df['media_muni']) / df['std_muni'], 0)
    df['es_anomalia'] = df['z_score'].abs() > 3

    n_anomalias = df['es_anomalia'].sum()
    pct = n_anomalias / len(df) * 100
    print(f"  {nombre_variable}: {n_anomalias:,} anomalias ({pct:.2f}%) de {len(df):,} registros")
    return df

df_temperatura = detectar_anomalias_por_municipio(df_temperatura, "Temperatura")
df_precipitacion = detectar_anomalias_por_municipio(df_precipitacion, "Precipitacion")
df_humedad = detectar_anomalias_por_municipio(df_humedad, "Humedad")

"""### 7c. Estandarizacion de nombres de municipio

Quitamos tildes y diacriticos para maximizar coincidencias entre datasets.
"""

def quitar_tildes(texto):
    if pd.isna(texto):
        return texto
    nfkd = unicodedata.normalize('NFKD', str(texto))
    return ''.join(c for c in nfkd if not unicodedata.combining(c))

print("Estandarizando nombres de municipio (quitando tildes)...\n")

df_desastres['municipio'] = df_desastres['municipio'].apply(quitar_tildes).str.upper().str.strip()
df_temperatura['municipio'] = df_temperatura['municipio'].apply(quitar_tildes).str.upper().str.strip()
df_precipitacion['municipio'] = df_precipitacion['municipio'].apply(quitar_tildes).str.upper().str.strip()
df_humedad['municipio'] = df_humedad['municipio'].apply(quitar_tildes).str.upper().str.strip()

df_desastres['tipo_de_evento'] = (
    df_desastres['tipo_de_evento']
    .str.strip().str.upper()
    .str.replace(r'\s+', ' ', regex=True)
)

munis_des = set(df_desastres['municipio'].dropna().unique())
munis_tmp = set(df_temperatura['municipio'].dropna().unique())
munis_prc = set(df_precipitacion['municipio'].dropna().unique())
munis_hum_set = set(df_humedad['municipio'].dropna().unique())
munis_clima_all = munis_tmp | munis_prc | munis_hum_set
coincidencias = munis_des & munis_clima_all

print(f"Municipios en desastres: {len(munis_des)}")
print(f"Municipios climaticos (union): {len(munis_clima_all)}")
print(f"Coincidencias directas: {len(coincidencias)} de {len(munis_des)}")
print(f"Municipios coincidentes: {sorted(coincidencias)}")

sin_clima = munis_des - munis_clima_all
if sin_clima:
    print(f"\nMunicipios con desastres SIN datos climaticos directos ({len(sin_clima)}):")
    print(sorted(sin_clima))

"""## 8. Cruce climatico vs desastres - Enfoque multi-nivel

### El problema
El cruce directo por municipio exacto + ventana de 7 dias solo cruza ~15 de ~966 eventos porque:
1. **Cobertura espacial limitada**: Las estaciones IDEAM solo existen en algunos municipios de Santander. La mayoria de municipios con desastres NO tienen estacion propia.
2. **Ventana temporal estrecha**: 7 dias es poco para encontrar registros exactos.

### La solucion: cruce multi-nivel

| Nivel | Estrategia | Precision espacial | Cobertura esperada |
|-------|-----------|-------------------|--------------------|
| 1 | Municipio exacto + promedio mensual | Alta | Baja (~15%) |
| 2 | Estacion mas cercana por coordenadas + promedio mensual | Media | Media (~60%) |
| 3 | Promedio departamental mensual | Baja (regional) | 100% |

Cada evento se cruza con el mejor nivel disponible, priorizando precision espacial.

### 8a. Diagnostico detallado del problema de cruce
"""

print("=" * 60)
print("DIAGNOSTICO: POR QUE HAY POCOS CRUCES?")
print("=" * 60)

# Cuantos eventos de desastre caen en municipios con estacion?
n_con_estacion = df_desastres['municipio'].isin(munis_clima_all).sum()
n_sin_estacion = len(df_desastres) - n_con_estacion

print(f"\nTotal eventos de desastre: {len(df_desastres)}")
print(f"Eventos en municipios CON estacion climatica: {n_con_estacion} ({n_con_estacion/len(df_desastres)*100:.1f}%)")
print(f"Eventos en municipios SIN estacion climatica: {n_sin_estacion} ({n_sin_estacion/len(df_desastres)*100:.1f}%)")

print(f"\n--- Top 15 municipios con mas desastres y su cobertura ---")
top_munis = df_desastres['municipio'].value_counts().head(15)
for muni, count in top_munis.items():
    tiene_t = 'T' if muni in munis_tmp else '-'
    tiene_p = 'P' if muni in munis_prc else '-'
    tiene_h = 'H' if muni in munis_hum_set else '-'
    print(f"  {muni:25s}: {count:3d} desastres  [{tiene_t}{tiene_p}{tiene_h}]")
print("  [T=temperatura, P=precipitacion, H=humedad]")

# Rangos temporales
print(f"\n--- Rangos temporales ---")
print(f"Desastres:     {fecha_min.date()} a {fecha_max.date()}")
for df_c, nombre in [(df_temperatura, 'Temperatura'), (df_precipitacion, 'Precipitacion'), (df_humedad, 'Humedad')]:
    if len(df_c) > 0:
        print(f"{nombre:15s}{df_c['fechaobservacion'].min().date()} a {df_c['fechaobservacion'].max().date()}")

print(f"\n>> CONCLUSION: La mayoria de municipios con desastres NO tienen")
print(f">> estacion climatica propia. Necesitamos un enfoque multi-nivel.")

"""### 8b. Construccion del mapeo de estacion mas cercana

Usamos las **coordenadas de las estaciones climaticas** para construir un mapeo: cada municipio de desastre se asocia al municipio climatico mas cercano geograficamente. Esto permite que un desastre en un municipio sin estacion use datos de la estacion vecina mas proxima.
"""

print("=" * 60)
print("MAPEO DE ESTACION MAS CERCANA POR COORDENADAS")
print("=" * 60)

def haversine(lon1, lat1, lon2, lat2):
    """Distancia en km entre dos puntos geograficos."""
    lon1, lat1, lon2, lat2 = map(radians, [float(lon1), float(lat1), float(lon2), float(lat2)])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    return 2 * 6371 * asin(sqrt(a))

# Paso 1: Obtener coordenadas promedio por municipio desde datos climaticos
# (cada estacion reporta lat/lon; promediamos por municipio)
coords_frames = []
for df_c, nombre in [(df_temperatura, 'temp'), (df_precipitacion, 'prec'), (df_humedad, 'hum')]:
    if len(df_c) > 0 and 'latitud' in df_c.columns and 'longitud' in df_c.columns:
        coords = df_c.dropna(subset=['latitud', 'longitud']).groupby('municipio').agg(
            lat=('latitud', 'mean'),
            lon=('longitud', 'mean'),
            n_estaciones=('codigoestacion', 'nunique') if 'codigoestacion' in df_c.columns else ('latitud', 'count')
        ).reset_index()
        coords_frames.append(coords)

if coords_frames:
    # Unir coordenadas de todas las fuentes
    coords_clima = pd.concat(coords_frames).groupby('municipio').agg(
        lat=('lat', 'mean'),
        lon=('lon', 'mean')
    ).reset_index()
    print(f"\nMunicipios climaticos con coordenadas: {len(coords_clima)}")
    display(coords_clima.head(10))
else:
    coords_clima = pd.DataFrame(columns=['municipio', 'lat', 'lon'])
    print("No se encontraron coordenadas en los datos climaticos.")

# Paso 2: Para cada municipio de desastre SIN estacion, encontrar el mas cercano
# que SI tenga datos climaticos
munis_sin_estacion = munis_des - munis_clima_all
munis_con_estacion = munis_des & munis_clima_all

# Coordenadas de municipios con estacion
coords_dict = dict(zip(coords_clima['municipio'], zip(coords_clima['lat'], coords_clima['lon'])))

# Mapeo: municipio_desastre -> municipio_clima_mas_cercano
muni_mapping = {}

# Los que tienen estacion propia se mapean a si mismos
for m in munis_con_estacion:
    muni_mapping[m] = {'muni_clima': m, 'distancia_km': 0, 'nivel': 'directo'}

# Los que NO tienen estacion, buscar el mas cercano
# Usamos las coordenadas del dataset de desastres si estan disponibles
# Si no, intentamos inferir desde municipios cercanos en los datos climaticos

# Primero verificar si el dataset de desastres tiene coordenadas
desastres_tiene_coords = ('latitud' in df_desastres.columns and 'longitud' in df_desastres.columns)
if desastres_tiene_coords:
    df_desastres['latitud'] = pd.to_numeric(df_desastres['latitud'], errors='coerce')
    df_desastres['longitud'] = pd.to_numeric(df_desastres['longitud'], errors='coerce')

for muni_des in munis_sin_estacion:
    lat_des, lon_des = None, None

    # Intentar obtener coords desde datos de desastres
    if desastres_tiene_coords:
        coords_des = df_desastres[df_desastres['municipio'] == muni_des][['latitud', 'longitud']].dropna()
        if len(coords_des) > 0:
            lat_des = coords_des['latitud'].mean()
            lon_des = coords_des['longitud'].mean()

    # Si tenemos coordenadas del municipio de desastre, buscar la estacion mas cercana
    if lat_des is not None and lon_des is not None and not (np.isnan(lat_des) or np.isnan(lon_des)):
        min_dist = float('inf')
        nearest = None
        for muni_clima, (lat_c, lon_c) in coords_dict.items():
            try:
                d = haversine(lon_des, lat_des, lon_c, lat_c)
                if d < min_dist:
                    min_dist = d
                    nearest = muni_clima
            except:
                continue
        if nearest and min_dist < 100:  # Maximo 100km
            muni_mapping[muni_des] = {'muni_clima': nearest, 'distancia_km': round(min_dist, 1), 'nivel': 'cercano'}
        else:
            muni_mapping[muni_des] = {'muni_clima': None, 'distancia_km': None, 'nivel': 'departamental'}
    else:
        # Sin coordenadas, ira al nivel departamental
        muni_mapping[muni_des] = {'muni_clima': None, 'distancia_km': None, 'nivel': 'departamental'}

# Resumen del mapeo
df_mapping = pd.DataFrame([
    {'municipio_desastre': k, **v} for k, v in muni_mapping.items()
])

print(f"\n--- Resumen del mapeo ---")
print(df_mapping['nivel'].value_counts().to_string())

print(f"\n--- Mapeo por cercania (municipios sin estacion propia) ---")
cercanos = df_mapping[df_mapping['nivel'] == 'cercano'].sort_values('distancia_km')
if len(cercanos) > 0:
    for _, row in cercanos.iterrows():
        print(f"  {row['municipio_desastre']:25s} -> {row['muni_clima']:20s} ({row['distancia_km']:.1f} km)")
else:
    print("  Ninguno (no hay coordenadas disponibles en datos de desastres)")

dept_munis = df_mapping[df_mapping['nivel'] == 'departamental']
if len(dept_munis) > 0:
    print(f"\n--- Municipios que usaran promedio departamental ({len(dept_munis)}) ---")
    print(f"  {sorted(dept_munis['municipio_desastre'].tolist())}")

"""### 8c. Agregacion mensual de datos climaticos

En lugar de buscar en una ventana estrecha de 7 dias, agregamos los datos climaticos a nivel **mensual**:
- **Por municipio**: media, desviacion estandar, minimo y maximo mensual
- **Departamental** (todo Santander): como fallback para municipios sin cobertura

Esto es mas robusto y captura las condiciones climaticas generales del mes en que ocurrio el desastre.
"""

print("=" * 60)
print("AGREGACION MENSUAL DE DATOS CLIMATICOS")
print("=" * 60)

def agregar_mensual(df_clima, nombre):
    """Calcula promedios mensuales por municipio y a nivel departamental."""
    if len(df_clima) == 0:
        return pd.DataFrame(), pd.DataFrame()

    # Por municipio
    por_muni = df_clima.groupby(
        [df_clima['fechaobservacion'].dt.to_period('M'), 'municipio']
    )['valorobservado'].agg(['mean', 'std', 'min', 'max', 'count']).reset_index()
    por_muni.columns = ['periodo', 'municipio',
                        f'{nombre}_media', f'{nombre}_std',
                        f'{nombre}_min', f'{nombre}_max', f'{nombre}_n']

    # Departamental (todo Santander)
    por_dept = df_clima.groupby(
        df_clima['fechaobservacion'].dt.to_period('M')
    )['valorobservado'].agg(['mean', 'std', 'min', 'max']).reset_index()
    por_dept.columns = ['periodo',
                        f'{nombre}_media_dept', f'{nombre}_std_dept',
                        f'{nombre}_min_dept', f'{nombre}_max_dept']

    print(f"  {nombre}: {len(por_muni)} registros municipio-mes, "
          f"{len(por_dept)} meses a nivel departamental")
    return por_muni, por_dept

temp_muni, temp_dept = agregar_mensual(df_temperatura, 'temp')
prec_muni, prec_dept = agregar_mensual(df_precipitacion, 'prec')
hum_muni, hum_dept = agregar_mensual(df_humedad, 'hum')

print(f"\nEjemplo - temperatura mensual por municipio:")
if len(temp_muni) > 0:
    display(temp_muni.head(5))

"""### 8d. Cruce multi-nivel: construir el dataset final

Para cada evento de desastre:
1. **Nivel 1 (directo)**: Si el municipio tiene estacion propia, usar su promedio mensual
2. **Nivel 2 (cercano)**: Si no, usar el promedio mensual de la estacion mas cercana por coordenadas
3. **Nivel 3 (departamental)**: Si no hay cercana, usar el promedio mensual de todo Santander
"""

print("=" * 60)
print("CONSTRUYENDO DATASET CRUZADO MULTI-NIVEL")
print("=" * 60)

# Preparar columnas en desastres
df_desastres['periodo'] = df_desastres['fecha_de_ocurrencia'].dt.to_period('M')

# Agregar columna de municipio climatico (segun mapeo)
mapping_dict = {k: v['muni_clima'] for k, v in muni_mapping.items()}
nivel_dict = {k: v['nivel'] for k, v in muni_mapping.items()}
dist_dict = {k: v['distancia_km'] for k, v in muni_mapping.items()}

df_desastres['muni_clima'] = df_desastres['municipio'].map(mapping_dict)
df_desastres['nivel_match'] = df_desastres['municipio'].map(nivel_dict)
df_desastres['distancia_estacion_km'] = df_desastres['municipio'].map(dist_dict)

print(f"\nDistribucion de niveles de match:")
print(df_desastres['nivel_match'].value_counts().to_string())

# Comenzar con copia de desastres
df_cruce = df_desastres.copy()

# Funcion para hacer el merge multi-nivel de una variable
def merge_clima_multinivel(df_cruce, muni_data, dept_data, nombre):
    """Merge con datos municipales (nivel 1 y 2) + fallback departamental (nivel 3)."""
    if len(muni_data) == 0 and len(dept_data) == 0:
        print(f"  {nombre}: sin datos disponibles")
        return df_cruce

    cols_valor = [f'{nombre}_media', f'{nombre}_std', f'{nombre}_min', f'{nombre}_max']

    # Merge nivel 1+2: datos por municipio (usando muni_clima del mapeo)
    if len(muni_data) > 0:
        df_cruce = df_cruce.merge(
            muni_data[['periodo', 'municipio'] + cols_valor + [f'{nombre}_n']],
            left_on=['periodo', 'muni_clima'],
            right_on=['periodo', 'municipio'],
            how='left',
            suffixes=('', f'_clima_{nombre}')
        )
        # Eliminar columna municipio duplicada del merge
        col_dup = f'municipio_clima_{nombre}'
        if col_dup in df_cruce.columns:
            df_cruce = df_cruce.drop(columns=[col_dup])

    # Merge nivel 3: datos departamentales
    if len(dept_data) > 0:
        df_cruce = df_cruce.merge(dept_data, on='periodo', how='left')

        # Rellenar nulos con promedios departamentales
        for col in cols_valor:
            col_dept = f'{col}_dept'
            if col in df_cruce.columns and col_dept in df_cruce.columns:
                df_cruce[col] = df_cruce[col].fillna(df_cruce[col_dept])
            elif col not in df_cruce.columns and col_dept in df_cruce.columns:
                df_cruce[col] = df_cruce[col_dept]

        # Eliminar columnas _dept
        dept_cols = [c for c in df_cruce.columns if c.endswith('_dept')]
        df_cruce = df_cruce.drop(columns=dept_cols)

    n_valid = df_cruce[f'{nombre}_media'].notna().sum() if f'{nombre}_media' in df_cruce.columns else 0
    print(f"  {nombre}: {n_valid} de {len(df_cruce)} eventos con datos ({n_valid/len(df_cruce)*100:.1f}%)")
    return df_cruce

print(f"\n--- Merging datos climaticos ---")
df_cruce = merge_clima_multinivel(df_cruce, temp_muni, temp_dept, 'temp')
df_cruce = merge_clima_multinivel(df_cruce, prec_muni, prec_dept, 'prec')
df_cruce = merge_clima_multinivel(df_cruce, hum_muni, hum_dept, 'hum')

# Marcar el nivel efectivo de cada variable
for nombre in ['temp', 'prec', 'hum']:
    n_col = f'{nombre}_n'
    media_col = f'{nombre}_media'
    nivel_col = f'{nombre}_nivel_efectivo'
    if n_col in df_cruce.columns and media_col in df_cruce.columns:
        df_cruce[nivel_col] = np.where(
            df_cruce[n_col].notna(),
            df_cruce['nivel_match'],  # Nivel 1 o 2 (tiene datos municipales)
            np.where(df_cruce[media_col].notna(), 'departamental', 'sin_datos')
        )
    elif media_col in df_cruce.columns:
        df_cruce[nivel_col] = np.where(
            df_cruce[media_col].notna(), 'departamental', 'sin_datos'
        )

print(f"\n{'='*60}")
print(f"RESULTADO DEL CRUCE MULTI-NIVEL")
print(f"{'='*60}")
print(f"\nDataset cruzado: {len(df_cruce)} eventos de desastre")

for nombre, label in [('temp', 'Temperatura'), ('prec', 'Precipitacion'), ('hum', 'Humedad')]:
    media_col = f'{nombre}_media'
    nivel_col = f'{nombre}_nivel_efectivo'
    if media_col in df_cruce.columns:
        n_total = df_cruce[media_col].notna().sum()
        print(f"\n  {label}: {n_total} eventos con datos ({n_total/len(df_cruce)*100:.1f}%)")
        if nivel_col in df_cruce.columns:
            print(f"    Por nivel: {df_cruce[nivel_col].value_counts().to_dict()}")

"""### 8e. Exploracion del dataset cruzado"""

# Columnas climaticas del cruce
cols_clima = [c for c in df_cruce.columns if any(
    c.startswith(p) for p in ['temp_', 'prec_', 'hum_']
) and not c.endswith('_efectivo')]

print("--- Primeras filas del dataset cruzado ---")
cols_mostrar = ['fecha_de_ocurrencia', 'municipio', 'tipo_de_evento',
                'nivel_match', 'muni_clima'] + \
               [c for c in ['temp_media', 'prec_media', 'hum_media'] if c in df_cruce.columns]
display(df_cruce[cols_mostrar].head(15))

print(f"\n--- Estadisticas del cruce por tipo de evento ---")
vars_media = [c for c in ['temp_media', 'prec_media', 'hum_media'] if c in df_cruce.columns]
if vars_media:
    resumen_tipo = df_cruce.groupby('tipo_de_evento')[vars_media].agg(['mean', 'count']).round(2)
    display(resumen_tipo)

print(f"\n--- Cruces por municipio (top 15) ---")
print(df_cruce.groupby('municipio')[vars_media[0]].agg(['count', 'mean']).sort_values('count', ascending=False).head(15).round(2).to_string())

"""### 8f. Condiciones climaticas por tipo de desastre

Comparamos las condiciones climaticas mensuales asociadas a cada tipo de desastre. Esto revela patrones diferenciados: por ejemplo, si las inundaciones coinciden con meses de alta precipitacion o si los incendios forestales ocurren en periodos secos.
"""

vars_media = [c for c in ['temp_media', 'prec_media', 'hum_media'] if c in df_cruce.columns]
n_vars = len(vars_media)

if n_vars > 0:
    # Top 5 tipos de desastre con mas datos
    top5_tipos = df_cruce['tipo_de_evento'].value_counts().head(5).index.tolist()
    data_top5 = df_cruce[df_cruce['tipo_de_evento'].isin(top5_tipos)].copy()

    nombres_legibles = {
        'temp_media': 'Temperatura media (\u00b0C)',
        'prec_media': 'Precipitacion media (mm)',
        'hum_media': 'Humedad media (%)'
    }

    fig, axes = plt.subplots(1, n_vars, figsize=(7*n_vars, 7))
    if n_vars == 1:
        axes = [axes]

    for i, var in enumerate(vars_media):
        data_plot = data_top5.dropna(subset=[var])
        if len(data_plot) > 0:
            sns.boxplot(data=data_plot, x='tipo_de_evento', y=var, ax=axes[i],
                        palette='Set2', order=top5_tipos)
            axes[i].set_title(nombres_legibles.get(var, var), fontweight='bold', fontsize=13)
            axes[i].set_xlabel('Tipo de evento')
            axes[i].set_ylabel('Valor mensual')
            axes[i].tick_params(axis='x', rotation=45)

    plt.suptitle('Condiciones climaticas mensuales por tipo de desastre',
                 fontsize=15, fontweight='bold', y=1.02)
    plt.tight_layout()
    plt.show()

    # Tabla resumen
    print("\n--- Tabla resumen: clima promedio por tipo de desastre ---")
    resumen = df_cruce.groupby('tipo_de_evento')[vars_media].mean().round(2)
    resumen['n_eventos'] = df_cruce.groupby('tipo_de_evento').size()
    resumen = resumen.sort_values('n_eventos', ascending=False)
    display(resumen)

"""## 9. Comparacion: clima en desastres vs periodos normales

**Pregunta clave:** Las condiciones climaticas mensuales son diferentes en meses con desastre vs meses sin desastre?

Usamos los promedios mensuales departamentales para comparar meses que tuvieron al menos un desastre vs meses sin desastres.
"""

print("=" * 60)
print("COMPARACION: CLIMA EN MESES CON DESASTRE vs MESES NORMALES")
print("=" * 60)

def comparar_meses_desastre_vs_normal(df_clima, df_eventos, nombre_variable):
    """Compara promedios mensuales en meses con/sin desastre."""
    if len(df_clima) == 0:
        return

    # Promedios mensuales departamentales
    mensual = df_clima.groupby(
        df_clima['fechaobservacion'].dt.to_period('M')
    )['valorobservado'].mean().reset_index()
    mensual.columns = ['periodo', 'valor']

    # Meses con al menos un desastre
    meses_desastre = set(df_eventos['fecha_de_ocurrencia'].dt.to_period('M').dropna())
    mensual['tiene_desastre'] = mensual['periodo'].isin(meses_desastre)

    n_con = mensual['tiene_desastre'].sum()
    n_sin = (~mensual['tiene_desastre']).sum()

    if n_con > 0 and n_sin > 0:
        media_con = mensual.loc[mensual['tiene_desastre'], 'valor'].mean()
        media_sin = mensual.loc[~mensual['tiene_desastre'], 'valor'].mean()
        std_sin = mensual.loc[~mensual['tiene_desastre'], 'valor'].std()

        print(f"\n{nombre_variable}:")
        print(f"  Promedio en meses CON desastre:  {media_con:.2f}  (n={n_con} meses)")
        print(f"  Promedio en meses SIN desastre:  {media_sin:.2f}  (n={n_sin} meses)")
        print(f"  Diferencia:                      {media_con - media_sin:+.2f}")
        if std_sin > 0:
            z = (media_con - media_sin) / std_sin
            print(f"  Diferencia en desviaciones std:  {z:+.2f}")

        fig, ax = plt.subplots(figsize=(10, 5))
        mensual.loc[~mensual['tiene_desastre'], 'valor'].hist(
            bins=20, ax=ax, alpha=0.6, color='#3498db',
            label=f'Sin desastre (n={n_sin})', density=True)
        mensual.loc[mensual['tiene_desastre'], 'valor'].hist(
            bins=20, ax=ax, alpha=0.6, color='#e74c3c',
            label=f'Con desastre (n={n_con})', density=True)
        ax.axvline(media_sin, color='#3498db', linestyle='--', linewidth=2)
        ax.axvline(media_con, color='#e74c3c', linestyle='--', linewidth=2)
        ax.set_title(f'{nombre_variable}: meses con desastre vs sin desastre', fontweight='bold')
        ax.set_xlabel(nombre_variable)
        ax.set_ylabel('Densidad')
        ax.legend()
        plt.tight_layout()
        plt.show()
    else:
        print(f"\n{nombre_variable}: datos insuficientes")

comparar_meses_desastre_vs_normal(df_temperatura, df_desastres, "Temperatura (\u00b0C)")
comparar_meses_desastre_vs_normal(df_precipitacion, df_desastres, "Precipitacion (mm)")
comparar_meses_desastre_vs_normal(df_humedad, df_desastres, "Humedad (%)")

"""## 10. Analisis de cobertura y limitaciones"""

print("=" * 60)
print("COBERTURA DEL CRUCE MULTI-NIVEL")
print("=" * 60)

print(f"\n--- Cobertura por nivel de match ---")
nivel_counts = df_cruce['nivel_match'].value_counts()
for nivel, count in nivel_counts.items():
    pct = count / len(df_cruce) * 100
    print(f"  {nivel:15s}: {count:4d} eventos ({pct:.1f}%)")

# Visualizacion
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Pie chart de niveles
colors_nivel = {'directo': '#27ae60', 'cercano': '#f39c12', 'departamental': '#3498db'}
nivel_counts.plot(kind='pie', ax=axes[0], autopct='%1.1f%%',
                  colors=[colors_nivel.get(n, '#95a5a6') for n in nivel_counts.index],
                  startangle=90)
axes[0].set_title('Distribucion de niveles de match', fontweight='bold')
axes[0].set_ylabel('')

# Cobertura por variable
cobertura = {}
for nombre, label in [('temp', 'Temperatura'), ('prec', 'Precipitacion'), ('hum', 'Humedad')]:
    col = f'{nombre}_media'
    if col in df_cruce.columns:
        cobertura[label] = df_cruce[col].notna().sum()

if cobertura:
    bars = axes[1].bar(cobertura.keys(), cobertura.values(),
                       color=['#e74c3c', '#3498db', '#27ae60'], edgecolor='black')
    axes[1].axhline(len(df_cruce), color='gray', linestyle='--',
                    label=f'Total eventos: {len(df_cruce)}')
    axes[1].set_title('Eventos con datos climaticos por variable', fontweight='bold')
    axes[1].set_ylabel('Cantidad de eventos')
    axes[1].legend()
    for bar, val in zip(bars, cobertura.values()):
        axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                     f'{val}', ha='center', fontweight='bold')

plt.tight_layout()
plt.show()

# Municipios sin cobertura
munis_sin = set(df_cruce[df_cruce['nivel_match'] == 'departamental']['municipio'].unique())
if munis_sin:
    print(f"\nMunicipios usando solo promedio departamental ({len(munis_sin)}):")
    for m in sorted(munis_sin):
        n = len(df_cruce[df_cruce['municipio'] == m])
        print(f"  {m}: {n} eventos")

"""## 11. Analisis de desbalanceo de clases

Evaluamos el desbalanceo entre periodos **con desastre** (clase 1) y **sin desastre** (clase 0) a nivel mensual por municipio.
"""

print("=" * 60)
print("DESBALANCEO DE CLASES")
print("=" * 60)

if len(df_temperatura) > 0:
    df_temperatura['anio_mes'] = df_temperatura['fechaobservacion'].dt.to_period('M')
    meses_clima = df_temperatura.groupby(['anio_mes', 'municipio']).size().reset_index(name='registros')
    n_periodos_total = len(meses_clima)

    df_desastres['anio_mes'] = df_desastres['fecha_de_ocurrencia'].dt.to_period('M')
    periodos_con_desastre = meses_clima.merge(
        df_desastres.groupby(['anio_mes', 'municipio']).size().reset_index(name='n_desastres'),
        on=['anio_mes', 'municipio'], how='inner'
    )
    n_periodos_desastre = len(periodos_con_desastre)
    n_periodos_normal = n_periodos_total - n_periodos_desastre
    ratio = n_periodos_normal / max(n_periodos_desastre, 1)

    print(f"\nPeriodos mensuales con datos climaticos: {n_periodos_total:,}")
    print(f"Periodos con al menos un desastre:       {n_periodos_desastre:,}")
    print(f"Periodos sin desastre (normales):        {n_periodos_normal:,}")
    print(f"Ratio de desbalanceo:                    {ratio:.1f}:1")

    fig, ax = plt.subplots(figsize=(8, 5))
    bars = ax.bar(['Sin desastre\n(clase 0)', 'Con desastre\n(clase 1)'],
                  [n_periodos_normal, n_periodos_desastre],
                  color=['#3498db', '#e74c3c'], edgecolor='black')
    ax.set_title('Desbalanceo de clases (periodos mensuales)', fontweight='bold', fontsize=14)
    ax.set_ylabel('Cantidad de periodos')
    for bar, val in zip(bars, [n_periodos_normal, n_periodos_desastre]):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                f'{val:,}', ha='center', fontweight='bold', fontsize=12)
    plt.tight_layout()
    plt.show()

    print(f"\n>> ESTRATEGIAS PARA MANEJAR EL DESBALANCEO:")
    print(f"   1. SMOTE: generar datos sinteticos de la clase minoritaria")
    print(f"   2. Submuestreo: reducir la clase mayoritaria")
    print(f"   3. Pesos de clase: penalizar mas los errores en la clase minoritaria")
    print(f"   4. Metricas adecuadas: usar F1-score, precision-recall, no solo accuracy")

"""## 12. Correlacion temporal entre variables

Correlacion mensual entre variables climaticas y frecuencia de desastres.
"""

print("=" * 60)
print("CORRELACION ENTRE VARIABLES CLIMATICAS - SANTANDER")
print("=" * 60)

monthly = {}
for df_c, nombre in [(df_temperatura, 'Temperatura'), (df_precipitacion, 'Precipitacion'), (df_humedad, 'Humedad')]:
    if len(df_c) > 0:
        monthly[nombre] = df_c.groupby(
            df_c['fechaobservacion'].dt.to_period('M')
        )['valorobservado'].mean()

if len(monthly) >= 2:
    df_monthly = pd.DataFrame(monthly).dropna()

    if len(df_desastres) > 0:
        des_monthly = df_desastres.groupby(
            df_desastres['fecha_de_ocurrencia'].dt.to_period('M')
        ).size()
        des_monthly.name = 'N_Desastres'
        df_monthly = df_monthly.join(des_monthly, how='left').fillna(0)

    print(f"Meses con datos cruzados: {len(df_monthly)}")

    if df_monthly.shape[1] >= 2:
        fig, axes = plt.subplots(1, 2, figsize=(16, 6))

        corr = df_monthly.corr()
        sns.heatmap(corr, annot=True, cmap='RdYlBu_r', center=0,
                    fmt='.3f', ax=axes[0], square=True, linewidths=1)
        axes[0].set_title('Correlacion mensual - Santander', fontweight='bold')

        if 'N_Desastres' in df_monthly.columns:
            ax1 = axes[1]
            idx = df_monthly.index.to_timestamp()
            if 'Precipitacion' in df_monthly.columns:
                ax1.bar(idx, df_monthly['Precipitacion'], alpha=0.4,
                        color='#3498db', label='Precipitacion (mm)')
            ax2 = ax1.twinx()
            ax2.plot(idx, df_monthly['N_Desastres'], color='#e74c3c',
                     marker='o', linewidth=2, label='N\u00b0 Desastres')
            ax2.set_ylabel('Desastres', color='#e74c3c')
            ax1.set_title('Precipitacion vs Desastres (mensual)', fontweight='bold')
            ax1.set_ylabel('Precipitacion (mm)')
            ax1.legend(loc='upper left')
            ax2.legend(loc='upper right')

        plt.tight_layout()
        plt.show()

        print("\nCorrelaciones:")
        print(corr.to_string())
else:
    print("Datos insuficientes para correlacion.")

"""## 13. Resumen de hallazgos

### 1. Alcance geografico
- El dataset de desastres cubre unicamente **Santander** (CAS y CDMB)

### 2. Tipos de desastre
- Los tipos mas frecuentes incluyen movimientos en masa, inundaciones, incendios forestales y avenidas torrenciales
- Cada tipo tiene diferentes relaciones con variables climaticas

### 3. Cruce multi-nivel
- El cruce directo (municipio exacto + 7 dias) solo cubria ~15 eventos
- Con la estrategia multi-nivel (municipio directo + estacion cercana + departamental mensual) se logra cobertura cercana al 100%
- Esto permite entrenar modelos con suficientes datos

### 4. Desbalanceo
- La gran mayoria de periodos NO tienen desastres
- Se requiere SMOTE, submuestreo o pesos de clase
- Metricas: F1-score, no accuracy

### 5. Cobertura
- Algunos municipios no tienen estacion propia y dependen de estaciones cercanas o promedios departamentales
- Las alertas en estos municipios seran menos precisas espacialmente

### 6. Implicaciones para el modelo
- **Variable objetivo:** presencia de desastre en un periodo-municipio
- **Features:** promedios mensuales de temp, precipitacion, humedad + anomalias + nivel de match
- **Granularidad:** mensual por municipio
- Se deben separar modelos o features por tipo de desastre

## 14. Relacion con la visita a la FAC

La FAC utiliza imagenes satelitales y modelos de IA para:
- Reconocimiento de mineria ilegal
- Identificacion de fuentes de CO2
- Alertas tempranas con cobertura espacial continua

### Conexion con nuestro proyecto

**1. Complementariedad de datos:**
- FAC: cobertura espacial continua (satelites) pero resolucion temporal limitada
- Nuestro proyecto: datos puntuales (estaciones IDEAM) con alta resolucion temporal
- Propuesta: un agente que fusione ambas fuentes mejoraria la cobertura

**2. Problema en comun - zonas ciegas:**
- Nuestro EDA revelo que algunos municipios de Santander no tienen estaciones
- Las imagenes satelitales de la FAC podrian llenar esos vacios

**3. Desde agentes inteligentes:**
- *Agente de fusion de datos:* combinar estaciones + satelites para interpolar
- *Agente de validacion cruzada:* usar detecciones satelitales como evidencia adicional en el modelo bayesiano
- *Agente de comunicacion:* generar reportes automaticos adaptados al nivel de urgencia

**4. Hallazgo especifico del EDA:**
- En Santander, los municipios sin cobertura climatica son exactamente los candidatos donde datos satelitales serian mas valiosos
- El enfoque multi-nivel del cruce (seccion 8) demuestra por que la fusion de fuentes es necesaria

---
# Pipeline ML — Sistema de Alertas Climáticas Tempranas
> Las celdas anteriores corresponden al EDA. Las siguientes ejecutan el pipeline ML completo.

# Pipeline ML — Sistema de Alertas Climáticas Tempranas · Santander

Notebook **autosuficiente**. Si el EDA ya fue ejecutado en el mismo kernel reutiliza
sus variables; si no, carga y procesa los datos directamente desde datos.gov.co.

---
## ⚠️ Crítica al EDA existente

| # | Problema | Impacto |
|---|----------|---------|
| 1 | **No se construye la variable objetivo.** `df_cruce` solo contiene filas de desastres (clase 1). Los meses sin desastre (clase 0) nunca se generan. | Imposible aprender la frontera de decisión sin ejemplos negativos. |
| 2 | **Sin features de rezago / rolling.** Los desastres resultan de acumulación climática, no del valor puntual del mes. | Pérdida masiva de señal predictiva. |
| 3 | **Z-score calculado pero nunca usado.** Se detectan anomalías por municipio y el dato no entra a ningún modelo. | El feature más informativo del EDA se desperdicia. |
| 4 | **Mes codificado como entero.** `mes=12` y `mes=1` son discontinuos para modelos lineales. | Sin/cos del mes elimina este artefacto. |
| 5 | **Sin split temporal.** K-Fold aleatorio filtra el futuro al pasado (data leakage). | Métricas de validación infladas artificialmente. |
| 6 | **Desbalanceo diagnosticado pero no tratado.** Ratio ~40:1 calculado; SMOTE mencionado pero no implementado. | Modelo que predice siempre clase 0 obtiene ~97 % accuracy sin aprender nada. |
| 7 | **Ningún modelo ML implementado.** El notebook termina en análisis descriptivo. | El objetivo del proyecto nunca se alcanza. |

## 0. Instalación
"""

!pip install imbalanced-learn scikit-learn scipy matplotlib seaborn pandas numpy sodapy -q
print("OK")

"""## 1. Imports"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings, unicodedata
from IPython.display import display

from sklearn.ensemble import (RandomForestClassifier, GradientBoostingClassifier,
                               RandomForestRegressor)
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    f1_score, precision_recall_curve, roc_auc_score,
    average_precision_score, classification_report,
    confusion_matrix, mean_absolute_error, mean_squared_error, r2_score
)
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from imblearn.over_sampling import SMOTE

warnings.filterwarnings('ignore')
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (14, 6)
plt.rcParams['font.size'] = 12
print("Imports OK")

"""---
## 2. Carga y preparación de datos (autosuficiente)

Detecta variables en memoria, descarga lo que falte y **siempre** recalcula los
agregados mensuales para garantizar consistencia de columnas.
"""

# ── Helpers (reproducidos del EDA) ──────────────────────────────────────────
def _quitar_tildes(texto):
    if pd.isna(texto):
        return texto
    nfkd = unicodedata.normalize('NFKD', str(texto))
    return ''.join(c for c in nfkd if not unicodedata.combining(c))

def _limpiar_climatico(df):
    df = df.copy()
    df['fechaobservacion'] = pd.to_datetime(df['fechaobservacion'], errors='coerce')
    df['valorobservado']   = pd.to_numeric(df['valorobservado'],   errors='coerce')
    for col in ['latitud', 'longitud']:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce')
    if 'municipio' in df.columns:
        df['municipio'] = df['municipio'].apply(_quitar_tildes).str.upper().str.strip()
    return df.dropna(subset=['fechaobservacion', 'valorobservado'])

def _agregar_mensual(df_c, prefix):
    '''Devuelve (muni_df, dept_df) con columnas prefix_media/_std/_min/_max/_n.'''
    if df_c is None or len(df_c) == 0:
        return pd.DataFrame(), pd.DataFrame()
    df_c = df_c.copy()
    df_c['fechaobservacion'] = pd.to_datetime(df_c['fechaobservacion'], errors='coerce')
    df_c['valorobservado']   = pd.to_numeric(df_c['valorobservado'], errors='coerce')
    df_c = df_c.dropna(subset=['fechaobservacion', 'valorobservado'])
    if 'municipio' in df_c.columns:
        df_c['municipio'] = df_c['municipio'].apply(_quitar_tildes).str.upper().str.strip()

    g_muni = df_c.groupby(
        [df_c['fechaobservacion'].dt.to_period('M'), 'municipio']
    )['valorobservado']
    muni = g_muni.agg(
        **{f'{prefix}_media': 'mean', f'{prefix}_std': 'std',
           f'{prefix}_min':  'min',  f'{prefix}_max': 'max',
           f'{prefix}_n':    'count'}
    ).reset_index()
    muni.rename(columns={'fechaobservacion': 'periodo'}, inplace=True)

    g_dept = df_c.groupby(
        df_c['fechaobservacion'].dt.to_period('M')
    )['valorobservado']
    dept = g_dept.agg(
        **{f'{prefix}_media_dept': 'mean', f'{prefix}_std_dept': 'std',
           f'{prefix}_min_dept':  'min',  f'{prefix}_max_dept': 'max'}
    ).reset_index()
    dept.rename(columns={'fechaobservacion': 'periodo'}, inplace=True)

    return muni, dept

print("Helpers definidos")

# ── Paso 2.1: DataFrames crudos ──────────────────────────────────────────────
_g = globals()
_RAW = {
    'df_desastres':     ('a4bc-a9tq', 5000),
    'df_temperatura':   ('sbwg-7ju4', 50000),
    'df_precipitacion': ('s54a-sgyg', 50000),
    'df_humedad':       ('uext-mhny', 50000),
}
_missing = [v for v in _RAW if v not in _g or len(_g[v]) == 0]

if _missing:
    print(f"Faltantes: {_missing}. Descargando de datos.gov.co...")
    from sodapy import Socrata
    _client = Socrata("www.datos.gov.co", None, timeout=120)

    for _var in _missing:
        _ds_id, _limit = _RAW[_var]
        print(f"  {_var} ({_ds_id})...", end=' ')

        if _var == 'df_desastres':
            _rows = _client.get(_ds_id, limit=_limit)
            _df   = pd.DataFrame.from_records(_rows)
            _df['autoridad_ambiental'] = _df['autoridad_ambiental'].str.upper().str.strip()
            _df = _df[_df['autoridad_ambiental'].isin(['CAS', 'CDMB'])].copy()
            _df['fecha_de_ocurrencia'] = pd.to_datetime(_df['fecha_de_ocurrencia'], errors='coerce')
            _df['municipio'] = _df['municipio'].apply(_quitar_tildes).str.upper().str.strip()
            for _c in ['familias_afectadas','viviendas_destruidas',
                        'viviendas_averiadas','heridos','fallecidos']:
                if _c in _df.columns:
                    _df[_c] = pd.to_numeric(_df[_c], errors='coerce').fillna(0)
        else:
            _frames = []
            for _yr in range(2020, 2025):
                _where = (f"departamento = 'SANTANDER' "
                          f"AND fechaobservacion >= '{_yr}-01-01T00:00:00' "
                          f"AND fechaobservacion < '{_yr+1}-01-01T00:00:00'")
                try:
                    _r = _client.get(_ds_id, where=_where, limit=_limit)
                    if _r:
                        _frames.append(pd.DataFrame.from_records(_r))
                except Exception as _e:
                    print(f"[{_yr} err:{_e}]", end=' ')
            _df = pd.concat(_frames, ignore_index=True) if _frames else pd.DataFrame()
            _df = _limpiar_climatico(_df)

        _g[_var] = _df
        print(f"{len(_df):,} filas")
else:
    print("DataFrames crudos ya en memoria:")
    for _v in _RAW:
        print(f"  {_v:24s}: {len(_g[_v]):,} filas")

# ── Paso 2.2: Agregados mensuales (siempre recalculados) ────────────────────
# Garantiza columnas consistentes independientemente de si vienen del EDA.
print("Calculando agregados mensuales...")
for _df_name, _prefix in [('df_temperatura','temp'),
                            ('df_precipitacion','prec'),
                            ('df_humedad','hum')]:
    _muni, _dept = _agregar_mensual(globals()[_df_name], _prefix)
    globals()[f'{_prefix}_muni'] = _muni
    globals()[f'{_prefix}_dept'] = _dept
    print(f"  {_prefix}_muni: {len(_muni):,} filas  |  "
          f"{_prefix}_dept: {len(_dept):,} filas")

# Verificación rápida de columnas
for _prefix in ['temp', 'prec', 'hum']:
    _m = globals()[f'{_prefix}_muni']
    _expected = [f'{_prefix}_media', f'{_prefix}_std',
                 f'{_prefix}_min',   f'{_prefix}_max', f'{_prefix}_n']
    _ok = all(c in _m.columns for c in _expected) if len(_m) > 0 else True
    print(f"  {_prefix}_muni columnas OK: {_ok}  {list(_m.columns)}")

"""---
## 3. Feature Engineering — Panel Municipio × Mes

### 3.1 Panel completo con variable objetivo binaria

El EDA solo tiene filas de desastres (clase 1).
Construimos el producto cartesiano municipio × mes e inicializamos todo a 0.
"""

# Recolectar municipios y períodos garantizados por Sección 2
all_periods, all_munis = set(), set()
for _prefix in ['temp', 'prec', 'hum']:
    _m = globals()[f'{_prefix}_muni']
    if len(_m) > 0:
        all_periods.update(_m['periodo'].dropna().unique())
        all_munis.update(_m['municipio'].dropna().unique())

if not all_periods:
    raise RuntimeError("temp/prec/hum_muni están vacíos. Revisa la Sección 2.")

# CRÍTICO 2: ampliar panel a todos los municipios con desastres registrados.
# Los municipios sin estación propia reciben el promedio departamental (fallback
# ya implementado en _merge_clima). Esto pasa de ~27 a ~94 municipios.
if 'df_desastres' in globals() and len(df_desastres) > 0:
    _munis_des = set(
        df_desastres['municipio'].dropna()
        .apply(_quitar_tildes).str.upper().str.strip().unique()
    )
    _munis_clima = set(all_munis)
    all_munis.update(_munis_des)
    print(f"Municipios con estación propia:              {len(_munis_clima)}")
    print(f"Municipios solo en desastres (fallback dpto): {len(_munis_des - _munis_clima)}")

all_periods = sorted(all_periods)
all_munis   = sorted(all_munis)
print(f"Municipios: {len(all_munis)}  |  Períodos: {len(all_periods)}  |  Panel: {len(all_munis)*len(all_periods):,}")

# Variable objetivo: 1 si hay ≥1 desastre en ese municipio-mes (TODOS los tipos)
df_des = df_desastres.copy()
df_des['periodo']   = pd.to_datetime(df_des['fecha_de_ocurrencia'], errors='coerce').dt.to_period('M')
df_des['municipio'] = df_des['municipio'].apply(_quitar_tildes).str.upper().str.strip()

# Mostrar distribución completa — todos los tipos contribuyen a y=1
print("Tipos de desastre incluidos en la variable objetivo (y=1):")
_tipo_col = 'tipo_de_evento' if 'tipo_de_evento' in df_des.columns else None
if _tipo_col:
    print(df_des[_tipo_col].value_counts().to_string())
else:
    print("  (columna tipo_de_evento no encontrada)")

target_df = df_des.groupby(['municipio', 'periodo']).size().reset_index(name='n_desastres')
target_df['desastre'] = 1

# Producto cartesiano → merge → relleno 0
panel = (pd.MultiIndex.from_product([all_munis, all_periods],
                                     names=['municipio', 'periodo'])
           .to_frame(index=False)
           .merge(target_df, on=['municipio', 'periodo'], how='left'))
panel['desastre']    = panel['desastre'].fillna(0).astype(int)
panel['n_desastres'] = panel['n_desastres'].fillna(0).astype(int)

n1 = panel['desastre'].sum()
n0 = (panel['desastre'] == 0).sum()
print(f"\nClase 1 (desastre):     {n1:,}  ({n1/len(panel)*100:.2f} %)")
print(f"Clase 0 (sin desastre): {n0:,} ({n0/len(panel)*100:.2f} %)")
print(f"Ratio desbalanceo:      {n0/max(n1,1):.1f}:1")

"""### 3.2 Merge datos climáticos (municipal + fallback departamental)"""

def _merge_clima(df, muni_df, dept_df, prefix):
    '''
    Left-join municipal; rellena NaN con el promedio departamental del mismo mes.
    Todas las columnas resultantes tienen el prefijo dado.
    '''
    cols_val = [f'{prefix}_media', f'{prefix}_std', f'{prefix}_min', f'{prefix}_max']

    # Nivel municipal
    if len(muni_df) > 0:
        avail = [c for c in ['periodo', 'municipio'] + cols_val if c in muni_df.columns]
        df = df.merge(muni_df[avail], on=['municipio', 'periodo'], how='left')

    # Nivel departamental (fallback)
    if len(dept_df) > 0:
        # Renombrar columnas dept para el merge temporal
        dept_renamed = dept_df.rename(columns={
            f'{prefix}_media_dept': f'_{prefix}_media_dept',
            f'{prefix}_std_dept':   f'_{prefix}_std_dept',
            f'{prefix}_min_dept':   f'_{prefix}_min_dept',
            f'{prefix}_max_dept':   f'_{prefix}_max_dept',
        })
        df = df.merge(dept_renamed, on='periodo', how='left')
        for col in cols_val:
            dcol = f'_{col}_dept'
            if col in df.columns and dcol in df.columns:
                df[col] = df[col].fillna(df[dcol])
            elif col not in df.columns and dcol in df.columns:
                df[col] = df[dcol]
        df.drop(columns=[c for c in df.columns if c.startswith('_') and c.endswith('_dept')],
                inplace=True, errors='ignore')
    return df

panel = _merge_clima(panel, temp_muni, temp_dept, 'temp')
panel = _merge_clima(panel, prec_muni, prec_dept, 'prec')
panel = _merge_clima(panel, hum_muni,  hum_dept,  'hum')

for p in ['temp', 'prec', 'hum']:
    col = f'{p}_media'
    n   = panel[col].notna().sum() if col in panel.columns else 0
    print(f"  {col}: {n:,} / {len(panel):,} ({n/len(panel)*100:.1f} %)")

"""### 3.3 Features de rezago, rolling y anomalía

- **Lags 1-3:** acumulación climática previa al desastre.
- **Rolling 3-6 meses:** tendencia reciente (shift(1) evita leakage del mes actual).
- **Z-score por municipio:** desviación respecto al histórico local.
- **Sin/cos del mes:** codificación cíclica continua (corrige la discontinuidad dic→ene).
- **Desastre lag-1 y lag-2:** autoregresivo del target.
"""

panel = panel.sort_values(['municipio', 'periodo']).reset_index(drop=True)

for col in [c for c in ['temp_media', 'prec_media', 'hum_media'] if c in panel.columns]:
    grp = panel.groupby('municipio')[col]
    for lag in [1, 2, 3]:
        panel[f'{col}_lag{lag}'] = grp.shift(lag)
    for w in [3, 6]:
        panel[f'{col}_roll{w}'] = grp.transform(
            lambda x: x.shift(1).rolling(w, min_periods=1).mean())
    mu    = grp.transform('mean')
    sigma = grp.transform('std').fillna(1).replace(0, 1)
    panel[f'{col}_zscore'] = (panel[col] - mu) / sigma
    panel[f'{col}_pct']    = grp.transform(lambda x: x.rank(pct=True))

panel['mes_num']            = panel['periodo'].dt.month
panel['anio']               = panel['periodo'].dt.year
panel['sin_mes']            = np.sin(2 * np.pi * panel['mes_num'] / 12)
panel['cos_mes']            = np.cos(2 * np.pi * panel['mes_num'] / 12)
panel['temporada_lluviosa'] = panel['mes_num'].isin([4, 5, 10, 11]).astype(int)
panel['desastre_lag1']      = panel.groupby('municipio')['desastre'].shift(1).fillna(0).astype(int)
panel['desastre_lag2']      = panel.groupby('municipio')['desastre'].shift(2).fillna(0).astype(int)

# Panel base: solo filas con al menos temp_media disponible
panel_model = panel.dropna(subset=['temp_media']).copy().reset_index(drop=True)

# FEATURE_COLS base (sin pred_* ni cluster_*, se añaden luego)
_NON_FEAT = {'municipio', 'periodo', 'desastre', 'n_desastres'}
FEATURE_COLS_BASE = [c for c in panel_model.columns if c not in _NON_FEAT]

print(f"Panel modelo: {len(panel_model):,} filas")
print(f"Features base: {len(FEATURE_COLS_BASE)}")
for f in FEATURE_COLS_BASE:
    print(f"  {f}")

"""---
## 4. Split temporal

Definimos `cutoff_period` (80/20) antes de entrenar los modelos derivados
(regresión, clustering), que se ajustan **solo con datos de entrenamiento**.
"""

sorted_periods = sorted(panel_model['periodo'].unique())
cutoff_idx     = int(len(sorted_periods) * 0.8)
cutoff_period  = sorted_periods[cutoff_idx]

_mask_train = panel_model['periodo'] <  cutoff_period
_mask_test  = panel_model['periodo'] >= cutoff_period

print(f"Cutoff: {cutoff_period}")
print(f"Train:  {_mask_train.sum():,} filas  "
      f"({panel_model.loc[_mask_train,'desastre'].sum()} positivos)")
print(f"Test:   {_mask_test.sum():,} filas   "
      f"({panel_model.loc[_mask_test,'desastre'].sum()} positivos)")

"""---
## 5. Modelo de Regresión — Ventana Climática Futura

Predice `temp_t+1`, `prec_t+1`, `prec_t+3`.
- Se entrena **solo con datos de train** (sin leakage temporal).
- Se aplica sobre **todo `panel_model`** para generar features para el clasificador.
- La evaluación (MAE, R²) se hace sobre el conjunto de test.
"""

print("=" * 60)
print("MODELO REGRESION: Ventana climatica futura")
print("=" * 60)

REG_TARGETS = {
    'pred_temp_t1': ('temp_media', 1, 'C'),
    'pred_prec_t1': ('prec_media', 1, 'mm'),
    'pred_prec_t3': ('prec_media', 3, 'mm'),
}

reg_results = {}
n_plots = sum(1 for _, (s,_,_) in REG_TARGETS.items() if s in panel_model.columns)
fig, axes = plt.subplots(1, max(n_plots,1), figsize=(6*max(n_plots,1), 5))
if n_plots == 1: axes = [axes]
plot_idx = 0

for pred_col, (src_col, horizon, unit) in REG_TARGETS.items():
    if src_col not in panel_model.columns:
        print(f"  {pred_col}: {src_col} no disponible")
        continue

    df_r = panel_model.copy()
    df_r['_y'] = df_r.groupby('municipio')[src_col].shift(-horizon)
    df_r = df_r.dropna(subset=['_y', src_col])

    tr_r = df_r[df_r['periodo'] <  cutoff_period]
    te_r = df_r[df_r['periodo'] >= cutoff_period]

    if len(te_r) < 5:
        print(f"  {pred_col}: test insuficiente ({len(te_r)} filas)")
        continue

    Xtr_r = tr_r[FEATURE_COLS_BASE].fillna(0)
    ytr_r = tr_r['_y']
    Xte_r = te_r[FEATURE_COLS_BASE].fillna(0)
    yte_r = te_r['_y']

    rf_r = RandomForestRegressor(n_estimators=200, max_depth=8,
                                  min_samples_leaf=5, random_state=42, n_jobs=-1)
    rf_r.fit(Xtr_r, ytr_r)
    yp_r = rf_r.predict(Xte_r)

    mae  = mean_absolute_error(yte_r, yp_r)
    rmse = np.sqrt(mean_squared_error(yte_r, yp_r))
    r2   = r2_score(yte_r, yp_r)
    reg_results[pred_col] = {'model': rf_r, 'mae': mae, 'rmse': rmse, 'r2': r2}
    print(f"  {pred_col} (t+{horizon}m): MAE={mae:.3f} {unit}  RMSE={rmse:.3f}  R2={r2:.3f}")

    # solo añadir pred_* si el modelo supera predecir la media (R2 > 0).
    # R2 negativo: el modelo invierte la señal, es peor que la media global.
    if r2 > 0:
        panel_model[pred_col] = rf_r.predict(panel_model[FEATURE_COLS_BASE].fillna(0))
        print(f"    -> feature '{pred_col}' añadida al panel")
    else:
        print(f"    -> '{pred_col}' descartada (R2={r2:.3f} < 0 = peor que predecir la media)")

    ax = axes[plot_idx]; plot_idx += 1
    lims = [min(yte_r.min(), yp_r.min()), max(yte_r.max(), yp_r.max())]
    ax.scatter(yte_r.values, yp_r, alpha=0.3, color='#3498db', s=10)
    ax.plot(lims, lims, 'r--', linewidth=2)
    ax.set_xlabel(f'Real ({unit})'); ax.set_ylabel(f'Pred ({unit})')
    ax.set_title(f'{pred_col}  R2={r2:.3f}', fontweight='bold')

plt.suptitle('Regresion: Ventana Climatica Futura', fontsize=13, fontweight='bold')
plt.tight_layout(); plt.show()

"""---
## 6. Clustering Regional — Rareza como Feature

Perfil climático histórico (calculado sobre datos de **train**) por municipio →
K-Means → **distancia al centroide** = anomalía estructural del municipio.
"""

print("=" * 60)
print("CLUSTERING REGIONAL")
print("=" * 60)

PERF_COLS = [c for c in ['temp_media','prec_media','hum_media',
                           'temp_std', 'prec_std', 'hum_std']
             if c in panel_model.columns]

# Perfil basado solo en datos de train
perfil = (panel_model[panel_model['periodo'] < cutoff_period]
          .groupby('municipio')[PERF_COLS].mean().dropna())
print(f"Municipios con perfil completo: {len(perfil)}")

if len(perfil) >= 4:
    from sklearn.preprocessing import StandardScaler as _SS
    _sc_cl = _SS()
    X_cl = _sc_cl.fit_transform(perfil[PERF_COLS])

    K_MAX = min(10, len(perfil) // 2)
    sil_scores = []
    for k in range(2, K_MAX + 1):
        _lbl = KMeans(n_clusters=k, random_state=42, n_init=10).fit_predict(X_cl)
        sil_scores.append(
            silhouette_score(X_cl, _lbl) if len(np.unique(_lbl)) > 1 else -1)

    BEST_K = 2 + int(np.argmax(sil_scores))
    print(f"K optimo: {BEST_K}  (silhouette={max(sil_scores):.3f})")

    km = KMeans(n_clusters=BEST_K, random_state=42, n_init=20)
    perfil['cluster'] = km.fit_predict(X_cl)
    centroids = km.cluster_centers_

    dists = [np.linalg.norm(X_cl[i] - centroids[int(perfil.iloc[i]['cluster'])])
             for i in range(len(perfil))]
    perfil['dist_centroide'] = dists
    _mu, _sd = perfil['dist_centroide'].mean(), perfil['dist_centroide'].std() + 1e-8
    perfil['rareza_z'] = (perfil['dist_centroide'] - _mu) / _sd

    # Transformar todos los municipios del panel usando el scaler/kmeans entrenados en train
    _all_perfil = panel_model.groupby('municipio')[PERF_COLS].mean().dropna()
    _X_all = _sc_cl.transform(_all_perfil[PERF_COLS])
    _all_perfil['cluster'] = km.predict(_X_all)
    _all_perfil['dist_centroide'] = [
        np.linalg.norm(_X_all[i] - centroids[int(_all_perfil.iloc[i]['cluster'])])
        for i in range(len(_all_perfil))
    ]
    _all_perfil['rareza_z'] = (_all_perfil['dist_centroide'] - _mu) / _sd

    # Merge al panel_model
    panel_model = panel_model.merge(
        _all_perfil[['cluster','dist_centroide','rareza_z']].reset_index(),
        on='municipio', how='left')
    print("Columnas de clustering añadidas: cluster, dist_centroide, rareza_z")
    print("\nMunicipios mas atipicos:")
    display(_all_perfil.nlargest(5,'dist_centroide')[
        ['cluster','dist_centroide','rareza_z']+PERF_COLS[:3]].round(3))

    # Visualización silhouette
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(range(2, K_MAX+1), sil_scores, marker='o', color='#e74c3c', linewidth=2)
    ax.axvline(BEST_K, color='gray', linestyle='--', label=f'K={BEST_K}')
    ax.set_title('Seleccion de K - Silhouette', fontweight='bold')
    ax.set_xlabel('K'); ax.set_ylabel('Silhouette Score'); ax.legend()
    plt.tight_layout(); plt.show()
else:
    print(f"Municipios insuficientes ({len(perfil)}) para clustering.")

"""---
## 7. FEATURE_COLS final y split definitivo

`FEATURE_COLS` se define **ahora**, después de añadir predicciones de regresión
y métricas de clustering a `panel_model`. El split train/test y el scaler se
ajustan con esta lista definitiva.
"""

# FEATURE_COLS final: todas las columnas que no son identificadores ni target
_NON_FEAT = {'municipio', 'periodo', 'desastre', 'n_desastres'}
FEATURE_COLS = [c for c in panel_model.columns if c not in _NON_FEAT]

print(f"FEATURE_COLS final: {len(FEATURE_COLS)} features")
for f in FEATURE_COLS:
    print(f"  {f}")

# Split definitivo usando panel_model con todas las features
train = panel_model[panel_model['periodo'] <  cutoff_period].copy()
test  = panel_model[panel_model['periodo'] >= cutoff_period].copy()

X_train = train[FEATURE_COLS].fillna(0)
y_train = train['desastre']
X_test  = test[FEATURE_COLS].fillna(0)
y_test  = test['desastre']

# Reservar el 20% final del train (temporal) para busqueda de threshold
_val_n    = max(int(len(X_train) * 0.20), 1)
X_val_thr = X_train.iloc[-_val_n:].copy()
y_val_thr = y_train.iloc[-_val_n:].copy()
X_train   = X_train.iloc[:-_val_n].copy()
y_train   = y_train.iloc[:-_val_n].copy()

print(f"Train: {len(X_train):,}  |  positivos={y_train.sum()}  ({y_train.mean()*100:.2f} %)")
print(f"Val:   {len(X_val_thr):,}   |  positivos={y_val_thr.sum()}   ({y_val_thr.mean()*100:.2f} %)")
print(f"Test:  {len(X_test):,}   |  positivos={y_test.sum()}   ({y_test.mean()*100:.2f} %)")

"""---
## 8. Modelo 1 — Clasificación Supervisada (Riesgo Binario)

### 8.1 SMOTE + Scaler
"""

# Escalar PRIMERO sobre train original, luego SMOTE en espacio escalado
scaler         = StandardScaler()
X_train_sc_raw = scaler.fit_transform(X_train)
X_te_sc        = scaler.transform(X_test)
X_val_sc       = scaler.transform(X_val_thr)

min_pos = int(y_train.sum())
if min_pos >= 2:
    k_n = min(5, min_pos - 1)
    X_tr_sc, y_tr_res = SMOTE(random_state=42, k_neighbors=k_n).fit_resample(X_train_sc_raw, y_train)
    print(f"SMOTE: {len(X_tr_sc):,} muestras  "
          f"(cls0={(y_tr_res==0).sum():,}  cls1={(y_tr_res==1).sum():,})")
else:
    X_tr_sc, y_tr_res = X_train_sc_raw, y_train
    print("SMOTE omitido (muy pocos positivos)")

print(f"Scaler ajustado con {X_train.shape[1]} features")

"""### 8.2 Entrenamiento y evaluación (F1 + Precision-Recall)"""

MODELS = {
    'RandomForest': RandomForestClassifier(
        n_estimators=300,
        max_depth=10, min_samples_leaf=5, random_state=42, n_jobs=-1),
    'GradientBoosting': GradientBoostingClassifier(
        n_estimators=200, max_depth=4, learning_rate=0.05,
        subsample=0.8, random_state=42),
    'LogisticRegression': LogisticRegression(
        class_weight='balanced', max_iter=2000, C=0.5, random_state=42),
}

clf_results = {}
for name, model in MODELS.items():
    use_sc = True  # todos los modelos usan datos escalados (Scale -> SMOTE)
    Xtr = X_tr_sc
    Xte = X_te_sc

    model.fit(Xtr, y_tr_res)
    y_prob = model.predict_proba(Xte)[:, 1]

    # Busqueda de umbral optimo sobre VALIDACION (no test -- evita data leakage).
    _y_prob_val = model.predict_proba(X_val_sc)[:, 1]
    _thrs    = np.linspace(0.01, 0.99, 200)
    _f1_thrs = [f1_score(y_val_thr, (_y_prob_val >= t).astype(int), zero_division=0)
                for t in _thrs]
    best_thr = float(_thrs[np.argmax(_f1_thrs)])
    y_pred   = (y_prob >= best_thr).astype(int)

    f1  = f1_score(y_test, y_pred, zero_division=0)
    ap  = average_precision_score(y_test, y_prob)  if y_test.sum() > 0 else 0.0
    auc = roc_auc_score(y_test, y_prob) if (y_test.sum() > 0 and (y_test==0).sum() > 0) else 0.0

    clf_results[name] = {'model': model, 'use_sc': use_sc,
                          'y_pred': y_pred, 'y_prob': y_prob,
                          'f1': f1, 'ap': ap, 'auc': auc, 'threshold': best_thr}

    print(f"\n{'='*50}\n{name}")
    print(f"  Umbral optimo τ*={best_thr:.3f}")
    print(f"  F1={f1:.4f}  AP={ap:.4f}  AUC={auc:.4f}")
    print(classification_report(y_test, y_pred,
          target_names=['Sin desastre','Desastre'], zero_division=0))

BEST_CLF = max(clf_results, key=lambda k: clf_results[k]['f1'])
print(f"\n>>> Mejor (F1): {BEST_CLF}  F1={clf_results[BEST_CLF]['f1']:.4f}")

# Curvas Precision-Recall y Confusion Matrix
COLORS = {'RandomForest':'#e74c3c','GradientBoosting':'#3498db','LogisticRegression':'#27ae60'}
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

ax = axes[0]
for name, res in clf_results.items():
    if y_test.sum() > 0:
        prec, rec, _ = precision_recall_curve(y_test, res['y_prob'])
        ax.plot(rec, prec, label=f"{name}  AP={res['ap']:.3f}",
                color=COLORS.get(name), linewidth=2)
ax.axhline(y_test.mean(), color='gray', linestyle='--', alpha=0.7,
           label=f"Baseline (prev={y_test.mean():.3f})")
ax.set_xlabel('Recall'); ax.set_ylabel('Precision')
ax.set_title('Curvas Precision-Recall', fontweight='bold')
ax.legend(); ax.set_xlim([0,1]); ax.set_ylim([0,1])

ax = axes[1]
cm = confusion_matrix(y_test, clf_results[BEST_CLF]['y_pred'])
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
            xticklabels=['Pred: No','Pred: Si'],
            yticklabels=['Real: No','Real: Si'])
ax.set_title(f'Confusion Matrix — {BEST_CLF}', fontweight='bold')
plt.tight_layout(); plt.show()

# Importancia de features
if 'RandomForest' in clf_results:
    imp   = pd.Series(clf_results['RandomForest']['model'].feature_importances_,
                      index=FEATURE_COLS)
    top20 = imp.nlargest(20).sort_values()
    fig, ax = plt.subplots(figsize=(10, 8))
    top20.plot(kind='barh', ax=ax, color='#2ecc71', edgecolor='black')
    ax.set_title('Top-20 Features (RandomForest)', fontweight='bold', fontsize=13)
    ax.set_xlabel('Importancia Gini')
    plt.tight_layout(); plt.show()
    print("Top-20:")
    for f, v in imp.nlargest(20).items():
        print(f"  {f:40s}: {v:.5f}")

"""### 8.3 Clasificación por tipo de desastre"""

print("=" * 60)
print("CLASIFICACION POR TIPO DE DESASTRE (top-5)")
print("=" * 60)
print("El modelo principal usa y=1 para CUALQUIER tipo de desastre.")
print("Este análisis entrena un RF independiente por tipo.\n")

_tipo_col = 'tipo_de_evento' if 'tipo_de_evento' in df_des.columns else None
if _tipo_col is None:
    print("Columna tipo_de_evento no encontrada. Saltando análisis por tipo.")
else:
    tipo_metrics = []
    for tipo in df_des[_tipo_col].value_counts().head(5).index.tolist():
        _tipo_df = (df_des[df_des[_tipo_col] == tipo]
                    .groupby(['municipio','periodo']).size().reset_index(name='_cnt'))
        _tipo_df['target_tipo'] = 1

        _pm = panel_model.merge(_tipo_df[['municipio','periodo','target_tipo']],
                                 on=['municipio','periodo'], how='left')
        _pm['target_tipo'] = _pm['target_tipo'].fillna(0).astype(int)

        _tr = _pm[_pm['periodo'] < cutoff_period]
        _te = _pm[_pm['periodo'] >= cutoff_period]
        _ytr, _yte = _tr['target_tipo'], _te['target_tipo']

        if _ytr.sum() < 2 or _yte.sum() < 1:
            print(f"  {tipo}: omitido — train_pos={_ytr.sum()}, "
                  f"test_pos={_yte.sum()} (datos insuficientes para evaluar)")
            continue

        _kn = min(5, int(_ytr.sum()) - 1)
        try:
            _Xr, _yr = SMOTE(random_state=42, k_neighbors=_kn).fit_resample(
                             _tr[FEATURE_COLS].fillna(0), _ytr)
        except Exception:
            _Xr, _yr = _tr[FEATURE_COLS].fillna(0), _ytr

        _rf = RandomForestClassifier(n_estimators=100, class_weight='balanced',
                                      random_state=42, n_jobs=-1)
        _rf.fit(_Xr, _yr)
        _yprob = _rf.predict_proba(_te[FEATURE_COLS].fillna(0))[:, 1]

        # Búsqueda de umbral óptimo por tipo
        _thrs_t  = np.linspace(0.01, 0.99, 100)
        _best_t  = float(_thrs_t[np.argmax([f1_score(_yte, (_yprob>=t).astype(int),
                                                       zero_division=0) for t in _thrs_t])])
        _yp      = (_yprob >= _best_t).astype(int)
        _f1      = f1_score(_yte, _yp, zero_division=0)
        _ap      = average_precision_score(_yte, _yprob) if _yte.sum() > 0 else 0.0
        print(f"  {tipo[:40]:40s}  F1={_f1:.4f}  AP={_ap:.4f}  τ*={_best_t:.2f}")
        tipo_metrics.append({'tipo': tipo, 'f1': _f1, 'ap': _ap})

    if tipo_metrics:
        _df_tm = pd.DataFrame(tipo_metrics).set_index('tipo')
        fig, ax = plt.subplots(figsize=(12, 5))
        _df_tm[['f1','ap']].plot(kind='bar', ax=ax,
                                  color=['#e74c3c','#3498db'], edgecolor='black')
        ax.set_title('F1 y AP por tipo de desastre', fontweight='bold')
        ax.set_ylabel('Metrica'); ax.set_xticklabels(ax.get_xticklabels(), rotation=30)
        ax.legend(['F1-score','Avg Precision'])
        plt.tight_layout(); plt.show()

"""---
## 9. Modelo Bayesiano — Combinación de Evidencias

Prior: tasa base histórica de desastres.
Evidencias secuenciales vía likelihood ratios:
1. Probabilidad del clasificador
2. Rareza del municipio (distancia al centroide)
3. Anomalía en la precipitación predicha
"""

print("=" * 60)
print("MODELO BAYESIANO")
print("=" * 60)

PRIOR = float(y_train.mean())
print(f"Prior P(desastre): {PRIOR:.4f}  ({PRIOR*100:.2f} %)")

def bayesian_update(prior, p_clf, rareza_z=None, prec_anomaly=None):
    '''Actualización bayesiana secuencial vía likelihood ratios.'''
    eps = 1e-8
    prior_odds = prior / (1 - prior + eps)
    posteriors = np.empty(len(p_clf))
    for i, p in enumerate(p_clf):
        lr   = (p / (1 - p + eps)) / (prior / (1 - prior + eps))
        odds = lr * prior_odds
        if rareza_z is not None and i < len(rareza_z):
            rz = float(rareza_z[i]) if not np.isnan(float(rareza_z[i])) else 0.0
            odds *= (1.0 + 0.15 * max(0.0, rz))
        if prec_anomaly is not None and i < len(prec_anomaly):
            pa = float(prec_anomaly[i]) if not np.isnan(float(prec_anomaly[i])) else 0.0
            odds *= (1.0 + 0.10 * max(0.0, pa))
        posteriors[i] = odds / (1 + odds)
    return np.clip(posteriors, 0.0, 1.0)

# Probabilidades del mejor clasificador en test
# test ya tiene FEATURE_COLS (split definitivo de Sección 7)
_best = clf_results[BEST_CLF]
Xte_clf = X_te_sc if _best['use_sc'] else X_test
p_clf_te = _best['model'].predict_proba(Xte_clf)[:, 1]

rareza_te = test['rareza_z'].values         if 'rareza_z'          in test.columns else None
prec_an_te= test['prec_media_zscore'].values if 'prec_media_zscore' in test.columns else None

p_bayes = bayesian_update(PRIOR, p_clf_te, rareza_te, prec_an_te)

# Threshold optimo (maximiza F1)
thresholds   = np.linspace(0.01, 0.99, 200)
f1_per_thr   = [f1_score(y_test, (p_bayes >= t).astype(int), zero_division=0)
                for t in thresholds]
BEST_THR     = float(thresholds[int(np.argmax(f1_per_thr))])
y_pred_bayes = (p_bayes >= BEST_THR).astype(int)
F1_BAYES     = f1_score(y_test, y_pred_bayes, zero_division=0)
AP_BAYES     = average_precision_score(y_test, p_bayes) if y_test.sum() > 0 else 0.0
AUC_BAYES    = roc_auc_score(y_test, p_bayes) if (y_test.sum()>0 and (y_test==0).sum()>0) else 0.0

print(f"\nThreshold optimo: {BEST_THR:.3f}")
print(f"F1={F1_BAYES:.4f}  AP={AP_BAYES:.4f}  AUC={AUC_BAYES:.4f}")
print(classification_report(y_test, y_pred_bayes,
      target_names=['Sin desastre','Desastre'], zero_division=0))

fig, axes = plt.subplots(1, 2, figsize=(16, 5))
ax = axes[0]
ax.hist(p_bayes[y_test==0], bins=40, alpha=0.6, color='#3498db',
        label='Sin desastre', density=True)
ax.hist(p_bayes[y_test==1], bins=40, alpha=0.7, color='#e74c3c',
        label='Con desastre', density=True)
ax.axvline(BEST_THR, color='black', linestyle='--', linewidth=2,
           label=f'Umbral F1-optimo ({BEST_THR:.2f})')
ax.set_title('P(desastre | evidencia) — Bayesiano', fontweight='bold')
ax.set_xlabel('Probabilidad posterior'); ax.legend()

ax = axes[1]
ax.plot(thresholds, f1_per_thr, color='#2ecc71', linewidth=2)
ax.axvline(BEST_THR, color='red', linestyle='--',
           label=f'F1={F1_BAYES:.3f} @ {BEST_THR:.2f}')
ax.set_title('F1 vs Umbral', fontweight='bold')
ax.set_xlabel('Umbral'); ax.set_ylabel('F1-score'); ax.legend()

plt.suptitle('Modelo Bayesiano de Alertas', fontsize=14, fontweight='bold')
plt.tight_layout(); plt.show()

"""---
## 10. Cadenas de Markov — Transiciones entre Estados de Riesgo

3 estados: **Bajo** (<0.20), **Medio** (0.20–0.50), **Alto** (≥0.50).
La matriz de transición se estima solo con datos de entrenamiento.
"""

print("=" * 60)
print("CADENAS DE MARKOV")
print("=" * 60)

N_EST  = 3
ESTADOS = {0:'Bajo', 1:'Medio', 2:'Alto'}

# LEVE 1: calcular prob_train primero para derivar umbrales empíricos.
# Los umbrales fijos (0.20/0.50) no reflejan la distribución real de prob_d;
# usar percentiles 33/66 garantiza soporte balanceado en los tres estados.
_best    = clf_results[BEST_CLF]

# Calculate probabilities for the original 'train' DataFrame (1056 rows)
# 'train' variable holds the full training data before validation split.
# 'FEATURE_COLS' defines the features to be used.
# 'scaler' is already fitted.
X_train_original_for_prob = train[FEATURE_COLS].fillna(0)
prob_train = _best['model'].predict_proba(scaler.transform(X_train_original_for_prob))[:, 1]

THR_BAJO = float(np.percentile(prob_train, 33))
THR_ALTO = float(np.percentile(prob_train, 66))
print(f"Umbrales (percentiles empíricos 33/66):")
print(f"  THR_BAJO={THR_BAJO:.3f}  THR_ALTO={THR_ALTO:.3f}")

def asignar_estado(p):
    if p < THR_BAJO:  return 0
    if p < THR_ALTO:  return 1
    return 2

train_mc = train.copy()
train_mc['prob_d'] = prob_train
train_mc['estado'] = train_mc['prob_d'].apply(asignar_estado)

def calcular_transicion(df_est):
    counts = np.zeros((N_EST, N_EST), dtype=float)
    for _, grp in df_est.sort_values('periodo').groupby('municipio'):
        seq = grp['estado'].values
        for t in range(len(seq) - 1):
            s0, s1 = int(seq[t]), int(seq[t+1])
            if 0 <= s0 < N_EST and 0 <= s1 < N_EST:
                counts[s0, s1] += 1
    row_s = counts.sum(axis=1, keepdims=True)
    return np.where(row_s > 0, counts / row_s, 1.0/N_EST), counts

P_markov, counts_markov = calcular_transicion(train_mc)
labels = [ESTADOS[i] for i in range(N_EST)]

df_P = pd.DataFrame(P_markov,
    index=[f'De: {l}' for l in labels],
    columns=[f'A: {l}' for l in labels])
print("\nMatriz de transicion P:")
display(df_P.round(4))

# Estado estacionario
_evals, _evecs = np.linalg.eig(P_markov.T)
_idx = int(np.argmin(np.abs(_evals - 1.0)))
_stat = np.real(_evecs[:, _idx])
stationary = np.abs(_stat) / np.abs(_stat).sum()
print("\nDistribucion estacionaria:")
for i, p in enumerate(stationary):
    print(f"  {ESTADOS[i]}: {p:.4f} ({p*100:.2f} %)")

def predict_next_state(estado_actual, n_steps=1):
    v = np.zeros(N_EST); v[estado_actual] = 1.0
    for _ in range(n_steps):
        v = v @ P_markov
    return v

print("\nPrediccion de siguiente estado:")
for s in range(N_EST):
    d = predict_next_state(s)
    print(f"  HOY={ESTADOS[s]:6s}: " +
          "  ".join([f"P({ESTADOS[j]})={d[j]:.3f}" for j in range(N_EST)]))

fig, axes = plt.subplots(1, 2, figsize=(16, 6))
ax = axes[0]
sns.heatmap(P_markov, annot=True, fmt='.3f', cmap='YlOrRd',
            xticklabels=labels, yticklabels=labels, ax=ax,
            linewidths=0.5, vmin=0, vmax=1)
ax.set_title('Matriz de Transicion de Riesgo', fontweight='bold', fontsize=13)
ax.set_ylabel('Estado actual'); ax.set_xlabel('Estado siguiente')

ax = axes[1]
colors_e = ['#27ae60','#f39c12','#e74c3c']
bars = ax.bar(labels, stationary, color=colors_e, edgecolor='black', linewidth=1.2)
for bar, val in zip(bars, stationary):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
            f'{val:.3f}', ha='center', fontweight='bold', fontsize=12)
ax.set_title('Distribucion Estacionaria de Riesgo', fontweight='bold', fontsize=13)
ax.set_ylabel('Probabilidad a largo plazo')
ax.set_ylim(0, max(stationary) * 1.3)
plt.suptitle('Cadenas de Markov — Santander', fontsize=14, fontweight='bold')
plt.tight_layout(); plt.show()

"""---
## 11. Sistema Integrado de Alertas

Score = **0.7 × P_bayesiano + 0.3 × P_Markov(Alto en t+1)**

| Nivel | Score |
|-------|-------|
| ROJA | ≥ 0.50 |
| NARANJA | ≥ 0.25 |
| AMARILLA | ≥ 0.10 |
| SIN ALERTA | < 0.10 |
"""

ALERTA_THRS   = [('ALERTA ROJA',0.50),('ALERTA NARANJA',0.25),
                  ('ALERTA AMARILLA',0.10),('SIN ALERTA',0.00)]
ALERTA_COLORS = {'ALERTA ROJA':'#e74c3c','ALERTA NARANJA':'#e67e22',
                  'ALERTA AMARILLA':'#f1c40f','SIN ALERTA':'#27ae60'}

def nivel_alerta(score):
    for nivel, thr in ALERTA_THRS:
        if score >= thr:
            return nivel
    return 'SIN ALERTA'

# Snapshot en el ultimo periodo de test
# test ya tiene FEATURE_COLS completo
ultimo_periodo = test['periodo'].max()
snap = test[test['periodo'] == ultimo_periodo].copy()

if len(snap) > 0:
    X_snap  = snap[FEATURE_COLS].fillna(0)
    Xsn_clf = scaler.transform(X_snap) if _best['use_sc'] else X_snap
    p_clf_sn = _best['model'].predict_proba(Xsn_clf)[:, 1]

    rar_sn   = snap['rareza_z'].values          if 'rareza_z'          in snap.columns else None
    pan_sn   = snap['prec_media_zscore'].values  if 'prec_media_zscore' in snap.columns else None
    p_bay_sn = bayesian_update(PRIOR, p_clf_sn, rar_sn, pan_sn)

    estado_sn      = [asignar_estado(p) for p in p_bay_sn]
    p_alto_next_sn = [float(predict_next_state(e)[2]) for e in estado_sn]
    score_sn       = 0.70 * p_bay_sn + 0.30 * np.array(p_alto_next_sn)

    snap = snap.copy()
    snap['p_bayesiana']    = p_bay_sn
    snap['p_alto_sig_mes'] = p_alto_next_sn
    snap['score_alerta']   = score_sn
    snap['estado_actual']  = [ESTADOS[e] for e in estado_sn]
    snap['alerta']         = snap['score_alerta'].apply(nivel_alerta)

    dashboard = snap[['municipio','p_bayesiana','p_alto_sig_mes',
                       'score_alerta','estado_actual','alerta']].sort_values(
                       'score_alerta', ascending=False)
    cnt_alerta = snap['alerta'].value_counts()

    print(f"DASHBOARD DE ALERTAS — {ultimo_periodo}")
    print("=" * 60)
    display(dashboard.head(20).round(4))
    print("\nResumen:")
    for nivel, _ in ALERTA_THRS:
        print(f"  {nivel:20s}: {cnt_alerta.get(nivel,0):3d} municipios")
else:
    print("Sin datos en el periodo mas reciente de test.")

if len(snap) > 0:
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    ax = axes[0]
    niveles = [n for n, _ in ALERTA_THRS]
    vals    = [cnt_alerta.get(n,0) for n in niveles]
    bars    = ax.bar(niveles, vals,
                     color=[ALERTA_COLORS[n] for n in niveles],
                     edgecolor='black', linewidth=1.2)
    for bar, val in zip(bars, vals):
        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.1,
                str(val), ha='center', fontweight='bold')
    ax.set_title(f'Alertas por municipio — {ultimo_periodo}', fontweight='bold')
    ax.set_ylabel('Municipios'); ax.tick_params(axis='x', rotation=20)

    ax = axes[1]
    ax.hist(snap['score_alerta'], bins=30, color='#8e44ad', edgecolor='black', alpha=0.7)
    for nivel, thr in ALERTA_THRS[:-1]:
        ax.axvline(thr, color=ALERTA_COLORS[nivel], linestyle='--',
                   linewidth=2, label=f'{nivel} (>{thr:.2f})')
    ax.set_title('Distribucion del Score de Alerta', fontweight='bold')
    ax.set_xlabel('Score (0-1)'); ax.set_ylabel('Municipios'); ax.legend(fontsize=9)

    plt.suptitle('Sistema de Alertas Tempranas — Santander',
                 fontsize=15, fontweight='bold')
    plt.tight_layout(); plt.show()

"""---
## 12. Resumen comparativo de todos los modelos
"""

rows = []
for name, res in clf_results.items():
    rows.append({'Modelo':name,'Tipo':'Clasificacion',
                 'F1':res['f1'],'Avg-Precision':res['ap'],'AUC-ROC':res['auc']})
rows.append({'Modelo':'Bayesiano','Tipo':'Bayesiano+Clustering',
             'F1':F1_BAYES,'Avg-Precision':AP_BAYES,'AUC-ROC':AUC_BAYES})

df_sum = pd.DataFrame(rows)
print(df_sum.round(4).to_string(index=False))

fig, ax = plt.subplots(figsize=(13, 5))
x, w = np.arange(len(df_sum)), 0.25
for i, (col, label, color) in enumerate([('F1','F1-score','#e74c3c'),
                                           ('Avg-Precision','Avg Precision','#3498db'),
                                           ('AUC-ROC','AUC-ROC','#27ae60')]):
    bars = ax.bar(x + (i-1)*w, df_sum[col], w, label=label,
                  color=color, edgecolor='black')
    for bar in bars:
        h = bar.get_height()
        ax.text(bar.get_x()+bar.get_width()/2, h+0.01,
                f'{h:.3f}', ha='center', fontsize=8, rotation=90)

ax.set_xticks(x); ax.set_xticklabels(df_sum['Modelo'], rotation=15)
ax.set_ylabel('Metrica')
ax.set_title('Comparacion de Modelos — Alertas Tempranas Santander',
             fontweight='bold', fontsize=14)
ax.legend(); ax.set_ylim(0, 1.15)
plt.tight_layout(); plt.show()

print("\nPIPELINE COMPLETO.")
print("Modelos: Clasificacion (RF/GB/LR) | Regresion | Clustering | Bayesiano | Markov")
print("Sistema de alertas: 4 niveles (Roja/Naranja/Amarilla/Sin alerta)")
print("Metricas: F1-score + Precision-Recall (no accuracy)")